#yml文件方式演示

spring:
    datasource:
        name: test
        url: jdbc:mysql://192.1.46.55:3306/ydj
        username: root
        password: jlcxtest
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ydj.springtest.service.user.dao

